export const USER_SERVICE = 'USER_SERVICE';
export const PRODUCT_SERVICE = 'PRODUCT_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const COMPANY_SERVICE = 'COMPANY_SERVICE';
